apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-config-pv
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.pv.nfs.path }}
    server: {{ .Values.pv.nfs.server }}
